### ISSUE TITLE
Configure Dgraph database for DgraphDataAccessor

### ISSUE THREAD

**Issue by hsinpeng** [comake/solid-dgraph#3]
Hi @adlerfaulkner .

Your work helps me a lot for understanding how to plug customized module into CSS. Thank you.

I encounter a problem on running "npx community-solid-server -c ./config.json -m .", and the error message is as the following.
> 2022-03-29T05:41:24.520Z [DgraphDataAccessor] info: Initializing Dgraph Client
> 2022-03-29T05:41:24.561Z [ContainerInitializer] warn: Failed to create resource http://localhost:3000/: 14 UNAVAILABLE: No connection established
> 2022-03-29T05:41:26.148Z [ContainerInitializer] warn: Failed to create resource http://localhost:3000/.acl: Failed to initialize Dgraph database.
> 2022-03-29T05:41:26.148Z [ContainerInitializer] info: Initialized container http://localhost:3000/ with 0 resources.

I guess the reason is that there is no Dgraph instance on my computer for DgraphDataAccessor to connect with. Am I right?
However, I am kind of confused for configuring Dgraph database for DgraphDataAccessor.

Should I replace the following settings with the original "@id": "urn:solid-dgraph:default:DgraphDataAccessor" settings in "dgraph.json"?
>{
>  "@id": "urn:solid-dgraph:default:DgraphDataAccessor",
>  "comment": "The configuration to connect to the Dgraph instance.",
>  "DgraphDataAccessor:_configuration_connectionUri": "https://mySpecialConnectionUri",
>  "DgraphDataAccessor:_configuration_grpcPort": "1234",
>}

Or append the settings above inside the @graph section of "dgraph.json"?

**Comment by adlerfaulkner** [comment]
Yes, you definitely need to have a Dgraph instance running on your computer to use this. You can start one using this docker image: [comake/dgraph](https://hub.docker.com/r/comake/dgraph).

You can run a zero, alpha, and an instance of ratel (see [dgraph docs](https://dgraph.io/docs/dgraph-overview/)) using a docker compose file such as:
```
version: "3.7"
services:
  zero:
    image: comake/dgraph:latest
    volumes:
      - zero-data-volume:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero:5080
  alpha1:
    image: comake/dgraph:latest
    hostname: "alpha1"
    volumes:
      - alpha-data-volume:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    command: dgraph alpha --my=alpha1:7080 --zero=zero:5080 --security whitelist=172.0.0.0:172.255.255.255,192.0.0.0:192.255.255.255
  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
volumes:
  zero-data-volume:
  alpha-data-volume:
```
Name this file `docker-compose.yaml` then run it using `docker compose -f ./docker-compose.yaml up`

> Should I replace the following settings with the original "@id": "urn:solid-dgraph:default:DgraphDataAccessor" settings in "dgraph.json"?

No, you do not need to edit `dgraph.json`. These settings would go in the `@graph` section of the json file you use as the `--config` or `-c` command line arg when starting CSS. 
This would be the file you created when following the [readme instructions](https://github.com/comake/solid-dgraph#configure) saying:

> Create a config.json file from [this template](https://github.com/comake/solid-dgraph/blob/main/config-example.json), and fill out your settings.

However, you don't need to set these settings if you are running dgraph locally and haven't changed any of it's default ports.
